name: build

on:
  workflow_call:
  # Setting this enables manually triggering workflow in the GitHub UI
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch: { }

permissions: read-all

jobs:
  build_browser_tests:
    runs-on: ubuntu-latest
    steps:
    - name: check out ${{ env.GITHUB_REF }}
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build browser testing container
      uses: docker/build-push-action@v3
      with:
        context: browser-test
        file: playwright.Dockerfile
        load: true
        push: false
        tags: civiform-browser-test:latest
        cache-from: |
          civiform/civiform-browser-test:latest
          type=gha
        cache-to: type=gha
        outputs: type=docker,dest=/tmp/civiform-browser-test.tar
    - name: Upload civiform-browser-test artifact
      uses: actions/upload-artifact@v3
      with:
        name: civiform-browser-test
        path: /tmp/civiform-browser-test.tar
        retention-days: 1

  build_civifom-dev:
    runs-on: ubuntu-latest
    steps:
    - name: check out ${{ env.GITHUB_REF }}
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build test app container
      uses: docker/build-push-action@v3
      with:
        context: ./
        load: true
        push: false
        tags: civiform
        cache-from: |
          civiform/civiform-dev:latest
          type=gha
        cache-to: type=gha
        outputs: type=docker,dest=/tmp/civiform-dev.tar
    - name: Upload civiform-dev artifact
      uses: actions/upload-artifact@v3
      with:
        name: civiform-dev
        path: /tmp/civiform-dev.tar
        retention-days: 1

  build_civifom:
    runs-on: ubuntu-latest
    steps:
    - name: check out ${{ env.GITHUB_REF }}
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build test app container
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: prod.Dockerfile
        load: true
        push: false
        tags: civiform:prod
        cache-from: |
          civiform/civiform:latest
          type=gha
        cache-to: type=gha
        outputs: type=docker,dest=/tmp/civiform.tar
    - name: Upload civiform artifact
      uses: actions/upload-artifact@v3
      with:
        name: civiform
        path: /tmp/civiform.tar
        retention-days: 1
